spring.application.name=instaMart
spring.data.mongodb.uri=mongodb+srv://ab_raq2:abdul310316@cluster0.wrf9c.mongodb.net/items_db?retryWrites=true&w=majority
openrouter.api.key = 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
openrouter.base.url= https://openrouter.ai/api/v1/chat/completions
